version: '3'

networks:
  dev:

services:
  php:
    build: './php/'
    ports:
      - 8080:80
    volumes:
      - ./src/:/var/www/html/
    depends_on:
      - mysql
    networks:
      - dev

  mysql:
    image: mysql:latest
    networks:
      - dev
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=main
    ports:
      - 3306:3306
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin
    restart: always
    networks:
      - dev
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=
    depends_on:
      - mysql
