networks:
  dev:

services:
  apache:
    build: './apache/'
    ports:
      - 80:80
    volumes:
      - ./src/:/var/www/html/
    depends_on:
      - php
      - mysql
    networks:
      - dev
  php:
    build: './php/'
    networks:
      - dev
    volumes:
      - ./src/:/var/www/html/
  mysql:
    image: mysql:latest
    networks:
      - dev
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=main
    ports:
      - 3306:3306
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/

